<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ImportController extends Controller
{
    public function importStates()
    {
        $states = [
            [
                'fips'      => '01',
                'alpha2'    => 'AL',
                'state'     => 'Alabama',
            ],
            [
                'fips'      => '02',
                'alpha2'    => 'AK',
                'state'     => 'Alaska',
            ],
            [
                'fips'      => '04',
                'alpha2'    => 'AZ',
                'state'     => 'Arizona',
            ],
            [
                'fips'      => '05',
                'alpha2'    => 'AR',
                'state'     => 'Arkansas',
            ],
            [
                'fips'      => '06',
                'alpha2'    => 'CA',
                'state'     => 'California',
            ],
            [
                'fips'      => '08',
                'alpha2'    => 'CO',
                'state'     => 'Colorado',
            ],
            [
                'fips'      => '09',
                'alpha2'    => 'CT',
                'state'     => 'Connecticut',
            ],
            [
                'fips'      => '10',
                'alpha2'    => 'DE',
                'state'     => 'Deleware',
            ],
            [
                'fips'      => '11',
                'alpha2'    => 'DC',
                'state'     => 'District of Columbia',
            ],
            [
                'fips'      => '12',
                'alpha2'    => 'FL',
                'state'     => 'Florida',
            ],
            [
                'fips'      => '13',
                'alpha2'    => 'GA',
                'state'     => 'Georgia',
            ],
            [
                'fips'      => '66',
                'alpha2'    => 'GU',
                'state'     => 'Guam',
            ],
            [
                'fips'      => '15',
                'alpha2'    => 'HI',
                'state'     => 'Hawaii',
            ],
            [
                'fips'      => '16',
                'alpha2'    => 'ID',
                'state'     => 'Idaho',
            ],
            [
                'fips'      => '17',
                'alpha2'    => 'IL',
                'state'     => 'Illinois',
            ],
            [
                'fips'      => '18',
                'alpha2'    => 'IN',
                'state'     => 'Indiana',
            ],
            [
                'fips'      => '19',
                'alpha2'    => 'IA',
                'state'     => 'Iowa',
            ],
            [
                'fips'      => '20',
                'alpha2'    => 'KS',
                'state'     => 'Kansas',
            ],
            [
                'fips'      => '21',
                'alpha2'    => 'KY',
                'state'     => 'Kentucky',
            ],
            [
                'fips'      => '22',
                'alpha2'    => 'LA',
                'state'     => 'Louisiana',
            ],
            [
                'fips'      => '23',
                'alpha2'    => 'ME',
                'state'     => 'Maine',
            ],
            [
                'fips'      => '60',
                'alpha2'    => 'AS',
                'state'     => 'American Samoa',
            ],
            [
                'fips'      => '24',
                'alpha2'    => 'MD',
                'state'     => 'Maryland',
            ],
            [
                'fips'      => '25',
                'alpha2'    => 'MA',
                'state'     => 'Massachusetts',
            ],
            [
                'fips'      => '26',
                'alpha2'    => 'MI',
                'state'     => 'Michigan',
            ],
            [
                'fips'      => '27',
                'alpha2'    => 'MN',
                'state'     => 'Minnesota',
            ],
            [
                'fips'      => '28',
                'alpha2'    => 'MS',
                'state'     => 'Mississippi',
            ],
            [
                'fips'      => '29',
                'alpha2'    => 'MO',
                'state'     => 'Missouri',
            ],
            [
                'fips'      => '30',
                'alpha2'    => 'MT',
                'state'     => 'Montana',
            ],
            [
                'fips'      => '31',
                'alpha2'    => 'NE',
                'state'     => 'Nebraska',
            ],
            [
                'fips'      => '32',
                'alpha2'    => 'NV',
                'state'     => 'Nevada',
            ],
            [
                'fips'      => '33',
                'alpha2'    => 'NH',
                'state'     => 'New Hampshire',
            ],
            [
                'fips'      => '34',
                'alpha2'    => 'NJ',
                'state'     => 'New Jersey',
            ],
            [
                'fips'      => '35',
                'alpha2'    => 'NM',
                'state'     => 'New Mexico',
            ],
            [
                'fips'      => '36',
                'alpha2'    => 'NY',
                'state'     => 'New York',
            ],
            [
                'fips'      => '37',
                'alpha2'    => 'NC',
                'state'     => 'North Carolina',
            ],
            [
                'fips'      => '38',
                'alpha2'    => 'ND',
                'state'     => 'North Dakota',
            ],
            [
                'fips'      => '39',
                'alpha2'    => 'OH',
                'state'     => 'Ohio',
            ],
            [
                'fips'      => '40',
                'alpha2'    => 'OK',
                'state'     => 'Oklahoma',
            ],
            [
                'fips'      => '41',
                'alpha2'    => 'OR',
                'state'     => 'Oregon',
            ],
            [
                'fips'      => '42',
                'alpha2'    => 'PA',
                'state'     => 'Pennsylvania',
            ],
            [
                'fips'      => '72',
                'alpha2'    => 'PR',
                'state'     => 'Puerto Rico',
            ],
            [
                'fips'      => '44',
                'alpha2'    => 'RI',
                'state'     => 'Rhode Island',
            ],
            [
                'fips'      => '45',
                'alpha2'    => 'SC',
                'state'     => 'South Carolina',
            ],
            [
                'fips'      => '46',
                'alpha2'    => 'SD',
                'state'     => 'South Dakota',
            ],
            [
                'fips'      => '47',
                'alpha2'    => 'TN',
                'state'     => 'Tennessee',
            ],
            [
                'fips'      => '48',
                'alpha2'    => 'TX',
                'state'     => 'Texas',
            ],
            [
                'fips'      => '49',
                'alpha2'    => 'UT',
                'state'     => 'Utah',
            ],
            [
                'fips'      => '50',
                'alpha2'    => 'VT',
                'state'     => 'Vermont',
            ],
            [
                'fips'      => '51',
                'alpha2'    => 'VA',
                'state'     => 'Virginia',
            ],
            [
                'fips'      => '78',
                'alpha2'    => 'VI',
                'state'     => 'Virgin Islands of the U.S.',
            ],
            [
                'fips'      => '53',
                'alpha2'    => 'WA',
                'state'     => 'Washington',
            ],
            [
                'fips'      => '54',
                'alpha2'    => 'WV',
                'state'     => 'West Virginia',
            ],
            [
                'fips'      => '55',
                'alpha2'    => 'WI',
                'state'     => 'Wisconsin',
            ],
            [
                'fips'      => '56',
                'alpha2'    => 'WY',
                'state'     => 'Wyoming',
            ],
        ];
        
        DB::table('states')
            ->insert($states);
        
        return view('import', [
            'num'   => count($states)
        ]);
    }
    
    public function importInterests()
    {
        $interests  = [
            [
                'name'          => 'Storm Chasing',
                'slug'          => 'stormchasing',
                'slug_search'   => 'skywarn, stormspotting, stormspotters, tornadoes, tornados, weatherspotters, stormchaser, tornadochasing, tornadochaser, severeweather',
                'tag'           => 'Weather Enthousiasts who Dig Chasing Severe Weather',
                'image'         => 'https://midlandusa.com/wp-content/uploads/2019/02/47306314_10155588719101090_845245067022041088_o-700x457.jpg',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Cooking',
                'slug'          => 'cooking',
                'slug_search'   => 'food',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Grilling',
                'slug'          => 'grilling',
                'slug_search'   => 'cooking, food',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Homebrewing',
                'slug'          => 'homebrewing',
                'slug_search'   => 'homebrewingbeer beefcrafting craftbeer craftingbeer',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Skiing',
                'slug'          => 'skiing',
                'slug_search'   => 'wintersports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Snowboarding',
                'slug'          => 'snowboarding',
                'slug_search'   => 'wintersports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Leatherworking',
                'slug'          => 'leatherworking',
                'slug_search'   => 'leathercrafting',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Chess',
                'slug'          => 'chess',
                'slug_search'   => 'games boardgames strategygames',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Rocketry',
                'slug'          => 'rocketry',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Investing in Stocks',
                'slug'          => 'investinginstocks',
                'slug_search'   => 'stockinvesting stockmarketinvesting, makemoneyinstocks, makingmoneyinstocks, makingmoney, makemoneyfromhome',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Investing in Residential Real Estate',
                'slug'          => 'investinginresidentialrealestate',
                'slug_search'   => 'houseflipping, houseflippers, realestateinvesting, investinginrealestate, housebuyers, housebuying, flippinghouses, flipahouse, investinginhouses, houseinvesting, homeinvesting, residentialrealestateinvesting',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Investing in Commercial Real Estate',
                'slug'          => 'investingincommercialrealestate',
                'slug_search'   => 'realestateinvesting, commercialrealestateinvesting, commercialinvesting, apartmentinvesting, apartments, investinapartments, investinginapartments',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Day Trading',
                'slug'          => 'daytrading',
                'slug_search'   => 'daytradingstocks, daytradingoptions, daytradingfutures, daytradingforex, daytrader, makingmoney, makemoneyfromhome',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'High Frequency Trading',
                'slug'          => 'highfrequencytrading',
                'slug_search'   => 'quant, quantitativeanalysis, quantitativeanalytics, coding, programming, stocks, investing',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Trading Options',
                'slug'          => 'tradingoptions',
                'slug_search'   => 'optionstrading, optionstrader, makingmoney, makemoneyfromhome',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Trading Futures',
                'slug'          => 'tradingfutures',
                'slug_search'   => 'futurestrading, futurestrader, makingmoney, makemoneyfromhome',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Trading FOREX',
                'slug'          => 'tradingforex',
                'slug_search'   => 'forextrading, forextrader, makingmoney, makemoneyfromhome',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Lockpicking',
                'slug'          => 'lockpicking',
                'slug_search'   => 'pickinglocks',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Archery',
                'slug'          => 'archery',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Thrifting',
                'slug'          => 'thrifting, shopping, antiques, cheap',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Tattooing',
                'slug'          => 'tattooing',
                'slug_search'   => 'tattoos, bodyart, inked',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Bodybuilding',
                'slug'          => 'bodybuilding',
                'slug_search'   => 'workingout, weightlifting, liftingweights, losingweight, weightloss, fitness, gettingfit, gettinginshape, getinshape, getfit, exercise',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Rock Climbing',
                'slug'          => 'rockclimbing',
                'slug_search'   => 'rocksports, repelling',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Car Restoration',
                'slug'          => 'carrestoration',
                'slug_search'   => 'classiccarrestoration, classiccars, rebuildingcars, rebuildcars, restoringcars, restoringoldcars, automotiverestoration',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Motorcycle Restoration',
                'slug'          => 'motorcyclerestoration',
                'slug_search'   => 'classicmotorcyclerestoration, classicmotorcycles, rebuildingmotorcycles, rebuildmotorcycles, restoringmotorcycles, restoringoldmotorcycles, automotiverestoration',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Building Cars',
                'slug'          => 'buildingcars',
                'slug_search'   => 'hotrods, carbuilding, classiccars, prototypes',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Rugby',
                'slug'          => 'rugby',
                'slug_search'   => 'contactsports, sports, teamsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Soccer',
                'slug'          => 'soccer',
                'slug_search'   => 'football, sports, teamsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Baseball',
                'slug'          => 'baseball',
                'slug_search'   => 'sports, teamsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Basketball',
                'slug'          => 'basketball',
                'slug_search'   => 'sports, teamsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Football',
                'slug'          => 'football',
                'slug_search'   => 'americanfootball, sports, teamsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Volleyball',
                'slug'          => 'volleyball',
                'slug_search'   => 'sports, teamsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Polo',
                'slug'          => 'polo',
                'slug_search'   => 'sports, teamsports, horses',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Cricket',
                'slug'          => 'cricket',
                'slug_search'   => 'sports, teamsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Biking',
                'slug'          => 'biking',
                'slug_search'   => 'sports, cycling, bicycle',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Mountain Biking',
                'slug'          => 'mountainbiking',
                'slug_search'   => 'biking, sports, cycling, mountainbikeracing, bicycle',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Boxing',
                'slug'          => 'boxing',
                'slug_search'   => 'sports, fighting, combatsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Mixed Martial Arts',
                'slug'          => 'mixedmartialarts',
                'slug_search'   => 'mma, sports, fighting, combatsports, martialarts cagefighting, octodomefighting, octodomefights',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Taekwondo',
                'slug'          => 'taekwondo',
                'slug_search'   => 'sports, martialarts, fighting, combatsports, karate',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Jujitsu',
                'slug'          => 'jujitsu',
                'slug_search'   => 'jujutsu, sports, martialarts, fighting, combatsports, grappling',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Martial Arts',
                'slug'          => 'martialarts',
                'slug_search'   => 'sports, karate, fighting, combatsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Judo',
                'slug'          => 'judo',
                'slug_search'   => 'sports, martialarts, fighting, combatsports, grappling',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Ultimate / Disc Golf',
                'slug'          => 'ultimatediscgolf',
                'slug_search'   => 'discgolf, ultimate, ultimatedisc, frisbee, sports, teamsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Curling',
                'slug'          => 'curling',
                'slug_search'   => 'sports, teamsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Cheerleading',
                'slug'          => 'cheerleading',
                'slug_search'   => 'sports, teamsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Field Hocky',
                'slug'          => 'fieldhockey',
                'slug_search'   => 'sports, teamsports, hockey',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Ice Hockey',
                'slug'          => 'icehockey',
                'slug_search'   => 'sports, teamsports, hockey, wintersports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Inline Hockey',
                'slug'          => 'inlinehockey',
                'slug_search'   => 'sports, teamsports, hockey',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Riding Rollercoasters',
                'slug'          => 'ridingrollercoasters',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Gymnastics',
                'slug'          => 'gymnastics',
                'slug_search'   => 'sports, individualsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Gaming',
                'slug'          => 'gaming',
                'slug_search'   => 'esports, videogames, videogaming, multiplayervideogames, sports, teamsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Handball',
                'slug'          => 'handball',
                'slug_search'   => 'sports, teamsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Ice Skating',
                'slug'          => 'iceskating',
                'slug_search'   => 'figureskating, sports, wintersports, individualsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Inline Skating',
                'slug'          => 'inlineskating',
                'slug_search'   => 'sports, individualsports, rollerblades, rollerblading',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Lacrosse',
                'slug'          => 'lacrosse',
                'slug_search'   => 'sports, teamsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Softball',
                'slug'          => 'softball',
                'slug_search'   => 'sports teamsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Swimming',
                'slug'          => 'swimming',
                'slug_search'   => 'sports, teamsports, individualsports, syncronizedswimming, summersports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Tennis',
                'slug'          => 'tennis',
                'slug_search'   => 'sports, individualsports, summersports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Table Tennis',
                'slug'          => 'tabletennis',
                'slug_search'   => 'sports, individualsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Track and Field',
                'slug'          => 'trackandfield',
                'slug_search'   => 'sports, individualsports, running, track, sprints, sprinting, middledistancerunning, longdistancerunning, steeplechase, hurdles, relays, hurdling, relaying, runninghurdles, runningrelays, runningmiddledistance, runninglongdistance, runningsprings, longjumping, highjumping, triplejumping, polevaulting, discusthrowing, shotputting, shotputthrowing, javelinthrowing, hammerthrowing, decathlon, heptathlon, racewalking, marathon, runningmarathons, marathonrunning',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Wrestling',
                'slug'          => 'wrestling',
                'slug_search'   => 'grecoromanwrestling, sports, individualsports, wwf',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Bodyboarding',
                'slug'          => 'bodyboarding',
                'slug_search'   => 'skimboarding, watersports, sports, individualsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Water Polo',
                'slug'          => 'waterpolo',
                'slug_search'   => 'sports, watersports, teamsports, summersports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Snowshoeing',
                'slug'          => 'snowshoeing',
                'slug_search'   => 'sports, wintersports, individualsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Sledding / Snow Tubing',
                'slug'          => 'sledding',
                'slug_search'   => 'snowtubing, tubing, wintersports, sports, individualsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Tubing',
                'slug'          => 'tubing',
                'slug_search'   => 'rivertubing, sports, individual sports, watertubing, laketubing',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Magic',
                'slug'          => 'magic',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Paintball',
                'slug'          => 'paintball',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Robotics',
                'slug'          => 'robotics',
                'slug_search'   => 'electronicmodels, electronicmodeling, electronics, buildingrobots, multicomponentresponsivedevices, battleroyale',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Prepping',
                'slug'          => 'prepping',
                'slug_search'   => 'survival, survivalskills, survivaltraining',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Photography',
                'slug'          => 'photography',
                'slug_search'   => 'takingpictures, takingphotos',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Reading',
                'slug'          => 'reading',
                'slug_search'   => 'readingbooks',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Skateboarding',
                'slug'          => 'skateboarding',
                'slug_search'   => 'sports, individualsports, skating',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'BMX',
                'slug'          => 'bmx',
                'slug_search'   => 'sports, individualsports, bike, bicycling, biking, cycling',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Geocaching',
                'slug'          => 'geocaching',
                'slug_search'   => 'gps',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Knife Making',
                'slug'          => 'knifemaking',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Landscaping',
                'slug'          => 'landscaping',
                'slug_search'   => 'lawnandgarden',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Sculpting Stone',
                'slug'          => 'sculptingstone',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Music Production',
                'slug'          => 'musicproduction',
                'slug_search'   => 'electronicmusicproduction, engineering, soundtechnician, producer, soundman',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Writing',
                'slug'          => 'writing',
                'slug_search'   => 'writingbooks, writingpoetry, writingnovels, author, writeabook',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Darts',
                'slug'          => 'darts',
                'slug_search'   => 'sports, individualsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Boating',
                'slug'          => 'boating',
                'slug_search'   => 'sailing, canoeing',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Kayaking',
                'slug'          => 'kayaking',
                'slug_search'   => 'boating',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Flying Planes',
                'slug'          => 'flyingplanes',
                'slug_search'   => 'pilot, flyingairplanes',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Flying Helicopters',
                'slug'          => 'flyinghelicopters',
                'slug_search'   => 'pilot',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Flying Drones',
                'slug'          => 'flyingdrones',
                'slug_search'   => 'pilot',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Collecting Rocks and Minerals',
                'slug'          => 'collectingrocksandminerals',
                'slug_search'   => 'geology, rockcollections, rockrollecting',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Drawing',
                'slug'          => 'drawing',
                'slug_search'   => 'illustrating, illustration, illustrator',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Painting',
                'slug'          => 'painting',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Drafting',
                'slug'          => 'drafting',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Stenciling',
                'slug'          => 'stenciling',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Calligraphy',
                'slug'          => 'calligraphy',
                'slug_search'   => 'writing',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Mosaics',
                'slug'          => 'mosaics',
                'slug_search'   => 'crafts',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Scrapbooking',
                'slug'          => 'scrapbooking',
                'slug_search'   => 'crafts',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Die Cutting',
                'slug'          => 'diecutting',
                'slug_search'   => 'cricut, crafts, makingsigns, signmaking',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Woodworking',
                'slug'          => 'woodworking',
                'slug_search'   => 'woodcrafting, craftingwood, crafts, whittling, woodsculpture, woodsculpting, sculptingwood',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Wood Burning',
                'slug'          => 'woodburning',
                'slug_search'   => 'woodwriting, writingonwood, crafts',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Crafts',
                'slug'          => 'crafts',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Camping',
                'slug'          => 'camping',
                'slug_search'   => 'outdoors',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Making Candles',
                'slug'          => 'makingcandles',
                'slug_search'   => 'candlemaking',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Making Soap',
                'slug'          => 'makingsoap',
                'slug_search'   => 'soapmaking, soapcrafting, homemadesoaps, handmadesoaps, handmakesoap',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Sculpting Clay',
                'slug'          => 'sculptingclay',
                'slug_search'   => 'modelingclay, claymodeling, claysculpting',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Dollhouses',
                'slug'          => 'dollhouses',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Miniatures',
                'slug'          => 'miniatures',
                'slug_search'   => 'crafts',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Making Dolls',
                'slug'          => 'makingdolls',
                'slug_search'   => 'dollmaking, crafts',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Glass Blowing',
                'slug'          => 'glassblowing',
                'slug_search'   => 'blowingglass, glasssculpting, sculptingglass, glasscreations, glassdesigns',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Metallurgy',
                'slug'          => 'metallurgy, metalworking',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Making Models',
                'slug'          => 'makingmodels',
                'slug_search'   => 'modelmaking, modeling, modelkits, buildingmodels, modelcrafting',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Dress Making',
                'slug'          => 'dressmaking, makingdresses, seweingdresses, deisgningdresses, dressdesign',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Racing Cars',
                'slug'          => 'racingcars',
                'slug_search'   => 'automotiveracing, autoracing, indicar, nascar, motorsports, sports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Racing Motorcycles',
                'slug'          => 'racingmotorcycles',
                'slug_search'   => 'motocross, motorsports, automotiveracing, sports, autoracing',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Exercising',
                'slug'          => 'exercising',
                'slug_search'   => 'fitness, workingout, losingweight, gettinginshape, getinshape, gettingfit, getfit, loseweight, weightloss, exercise',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Crossfit',
                'slug'          => 'crossfit',
                'slug_search'   => 'fitness, workingout, losingweight, gettinginshape, getinshape, gettingfit, getfit, loseweight, weightloss, exercise',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Coding',
                'slug'          => 'coding',
                'slug_search'   => 'digitaldesign',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Web Development',
                'slug'          => 'webdevelopment',
                'slug_search'   => 'webdesign, websitedevelopment, websitedesign, buildingwebsites, designingwebsites, developmingwebsites, buildawebsite, coding',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Astronomy',
                'slug'          => 'astronomy',
                'slug_search'   => 'stargazing, gazingatstars, gazingatthestars',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Scotch Tasting',
                'slug'          => 'scotchtasting',
                'slug_search'   => 'tastingscotch, samplingscotch',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Wine Tasting',
                'slug'          => 'winetasting',
                'slug_search'   => 'tastingwine, samplingwine',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Beer Tasting',
                'slug'          => 'beertasting',
                'slug_search'   => 'tastingbeer, samplingbeer, beerhopping, barhopping',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Drinking',
                'slug'          => 'drinking',
                'slug_search'   => 'barhopping, drinks, drinkingtogether, enjoyingdrinkstogether',
                'tag'           => 'Let\'s Enjoy Drinks Together!',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Eating',
                'slug'          => 'eating',
                'slug_search'   => 'foodtasting, tastingfood, tryingfood, foodwriter, foodwriting, foodcritic, criticisingfood',
                'tag'           => 'A Place for Food Enthousiasts to Meet Up and Eat',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Billiards',
                'slug'          => 'billiards',
                'slug_search'   => 'pool',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Fantasy Sports',
                'slug'          => 'fantasysports',
                'slug_search'   => 'sports, fantasyfootball, gambling',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Gold Panning',
                'slug'          => 'goldpanning',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Fencing',
                'slug'          => 'fencing',
                'slug_search'   => 'sports, individualsports, combatsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Volunteering',
                'slug'          => 'volunteering',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Poker',
                'slug'          => 'poker',
                'slug_search'   => 'games, gambling, cardgames',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Card Games',
                'slug'          => 'cardgames',
                'slug_search'   => 'games, gambling, rummy, patience, uno, war, bridge, cribbage, ginrummy, poker',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Partying',
                'slug'          => 'partying',
                'slug_search'   => 'clubbing, houseparty',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Party Planning',
                'slug'          => 'partyplanning',
                'slug_search'   => 'planaparty, partyhosting, hostaparty, houseparty, hostahouseparty',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Wedding Planning',
                'slug'          => 'weddingplanning',
                'slug_search'   => 'weddingplanner, planningawedding, planningweddings, planmywedding',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Playing Instruments',
                'slug'          => 'playinginstruments',
                'slug_search'   => 'guitar, drums, keys, keyboard, jam, gig, band',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Golf',
                'slug'          => 'golf',
                'slug_search'   => 'golfing, sports, individualsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Coaching',
                'slug'          => 'coaching',
                'slug_search'   => 'beingacoach, beacoach, sports, teamsports, kidsteam',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Mentoring',
                'slug'          => 'mentoring',
                'slug_search'   => 'beingamentor, beamentor, finamentor',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Meditation',
                'slug'          => 'meditation',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Yoga',
                'slug'          => 'yoga',
                'slug_search'   => 'sports, individualsports, workingout, exercise',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Fishing',
                'slug'          => 'fishing',
                'slug_search'   => 'sports, individualsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Traveling',
                'slug'          => 'traveling',
                'slug_search'   => 'lovetotravel, goplaces, goingplaces, visitplaces, tourist, beatourist, sightseeing',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Fish',
                'slug'          => 'fish',
                'slug_search'   => 'fishkeeping, raisingfish, aquariums, pets, breedingfish, takecareoffish, takingcareoffish',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Dogs',
                'slug'          => 'dogs',
                'slug_search'   => 'pets, raisingdogs, breedingdogs, takecareofdogs, takingcareofdogs, dogwalking, dogwalker, walkingdogs, trainingdogs, traindogs, dogtraining, dogtrainer, howtotrainadog',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Cats',
                'slug'          => 'cats',
                'slug_search'   => 'pets, raisingcats, breedingcats, takecareofcats, takingcareofcats, trainingcats, traincats, howtotrainacat, cattraining, cattrainer',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Surfing',
                'slug'          => 'surfing',
                'slug_search'   => 'watersports, sports, individualsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Bowling',
                'slug'          => 'bowling',
                'slug_search'   => 'sports, indvidualsports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Interior Design',
                'slug'          => 'interiordesign',
                'slug_search'   => 'interiordeisgning, architect, architecting',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Realty',
                'slug'          => 'realty',
                'slug_search'   => 'realestate, realtor, sellhomes, sellinghomes, sellhouses, sellinghouses, professionalrealtors, professionalrealty, findarealtor',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Sightseeing',
                'slug'          => 'sightseeing',
                'slug_search'   => 'traveling',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Buying a Home',
                'slug'          => 'buyingahome',
                'slug_search'   => 'buyingahouse, firsttimehomebuyer, realtor, realestate, buyahome, buyahouse, buyinghomes, buyinghouses, homebuyingtips, howtobuyahouse',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Collecting Currency',
                'slug'          => 'collectingcurrency',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Collecting Coins',
                'slug'          => 'collectingcoins',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Foreign Languages',
                'slug'          => 'foreignlanguages',
                'slug_search'   => 'learnalanguage, learnanewlanguage, speakalanguage, speakinglanguages',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Genealogy',
                'slug'          => 'genealogy',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Smoking Cigars',
                'slug'          => 'smokingcigars',
                'slug_search'   => 'cigarenthusiast',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Watching Movies',
                'slug'          => 'watchingmovies',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Making Movies',
                'slug'          => 'makingmovies',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Special Effects',
                'slug'          => 'specialeffects',
                'slug_search'   => 'makingmovies, digitaldesign, digitaleffects',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Gardening',
                'slug'          => 'gardening',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Fashion Design',
                'slug'          => 'fashiondesign',
                'slug_search'   => 'fahiondesigning, fashiondesigner, designingfashion',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Snorkeling',
                'slug'          => 'snorkeling',
                'slug_search'   => 'sports, individualsports, watersports',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Dancing',
                'slug'          => 'dancing',
                'slug_search'   => 'sports, individualsports, teamsports, dancepartner, exercise',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Watchmaking',
                'slug'          => 'watchmaking',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Internet Marketing',
                'slug'          => 'internetmarketing',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Marketing',
                'slug'          => 'marketing',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Singing',
                'slug'          => 'singing',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Running',
                'slug'          => 'running',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Watching Theater',
                'slug'          => 'watchingtheater',
                'slug_search'   => 'theaterwatching, watchingplays, watchplays',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Theater Performing',
                'slug'          => 'theaterperforming',
                'slug_search'   => 'performance, performing',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Origami',
                'slug'          => 'origami',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Making Jewelry',
                'slug'          => 'makingjewelry',
                'slug_search'   => 'jewelrymaking, beading, craftingjewelry, designingjewelry, jewelrydesign',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Puzzles',
                'slug'          => 'puzzles',
                'slug_search'   => 'puttingpuzzlestogether, games, putapuzzletogether, puttogetherapuzzle, puttingtogetherpuzzles, puttingtogetherapuzzle',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Flower Arranging',
                'slug'          => 'flowerarranging',
                'slug_search'   => 'arrangingflowers',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Knitting',
                'slug'          => 'knitting',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Hiking',
                'slug'          => 'hiking',
                'slug_search'   => 'outdoors, exercise, exercising',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Cosplay',
                'slug'          => 'cosplay',
                'slug_search'   => 'characters, costumes, dressingup, costuming',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Church',
                'slug'          => 'church',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Bible Studies',
                'slug'          => 'biblestudies',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Christian Evangelism',
                'slug'          => 'christianevangelism',
                'slug_search'   => 'evangelizing',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Christian Healing',
                'slug'          => 'christianhealing',
                'slug_search'   => '',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Christian Worship',
                'slug'          => 'christianworship',
                'slug_search'   => 'praise',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Print on Demand',
                'slug'          => 'printondemand',
                'slug_search'   => 'makingmoney, makemoneyfromhome',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
            [
                'name'          => 'Dropshipping',
                'slug'          => 'dropshipping',
                'slug_search'   => 'makingmoney, makemoneyfromhome',
                'tag'           => '',
                'image'         => '',
                'created_at'    => \Carbon\Carbon::now(),
            ],
        ];
            
        DB::table('interests')
            ->insert($interests);
            
        return view('import', [
            'num'   => count($interests)
        ]);
    }
    
    public function importLocations()
    {
        ini_set('memory_limit','1G');
        ini_set('max_execution_time', '600');
        
        $fileLocation   = 'uploads/US.txt';
        
        $states     = DB::table('states')
            ->select('id', 'alpha2')
            ->get()
            ->keyBy('alpha2');
        $locations  = array();
        $file       = fopen($fileLocation, 'r');
        $i = 0;
        while (($line = fgets($file)) !== false) {
            $i++;
            if ($i <= 2200000) {
                continue;
            }
            if ($i > 2400000) {
                break;
            }
            $location   = preg_split("/\t/", $line);
            $locationData   = array(
                'slug'              => strtolower(preg_replace('/\s/', '', $location[2])),
                'name'              => $location[2],
                'alternatenames'    => $location[3],
                'latitude'          => $location[4],
                'longitude'         => $location[5],
                'slug_search'       => strtolower(str_replace(',', ' ', (preg_replace('/\s/', '', $location[3])))),
                'created_at'        => \Carbon\Carbon::now(),
            );
            if (isset($states[$location[10]])) {
                $locationData['state_id']   = $states[$location[10]]->id;
            } else {
                $locationData['state_id']   = 0;
            }
            $locations[]    = $locationData;
            if ($i % 5000 == 0) {
                DB::table('locations')
                    ->insert($locations);
                $locations  = array();
            }
        }
        if (count($locations)) {
            DB::table('locations')
                ->insert($locations);
        }
        fclose($file);
        
        return view('import', [
            'num'   => $i
        ]);
    }
    
}